stages:
  download:
    cmd: python -m src.training.download_data
    deps:
      - src/training/download_data.py
    outs:
      - data/raw

  process:
    cmd: python -m src.training.process_data
    deps:
      - src/training/process_data.py
      - data/raw
    outs:
      - data/processed

  train:
    cmd: python -m src.training.train
    deps:
      - src/training/train.py
      - data/processed
    params:
      - conf/config.yaml:
          - hyperparams
          - model
    outs:
      - models/

  evaluate:
    cmd: python -m src.training.evaluate
    deps:
      - src/training/evaluate.py
      - models/
      - data/processed
    metrics:
      - reports/xgb-cat/evaluation_report.json:
          cache: false